### PR TITLE
fix(memory): ensure thumbnails are images and resizable

### LINKED ISSUE #42: Fatal error - OOM on specific link
This link: http://www.vox.com/conversations/2017/2/15/14597774/evan-mcmullin-donald-trump-cia-republican-party-intelligence-community

creates a fatal error (OOM) for as-yet-unknown reasons

### PR DESCRIPTION
**Pull request by beck24**
fixes #42
Prevents an infinite loop when thumbnail urls are not actually images.  Also checks that
the system has enough memory to handle an image resize operation.

### CODE REVIEW

File: classes/hypeJunction/Scraper/ScraperService.php [hunk 1]
```diff
@@ -311,21 +318,18 @@ public function parseThumbs(array $data = []) {
...
+		$thumbnails = array_filter(array_unique($thumbnails + $icons));
+		$thumbs_parsed = 0;
 		foreach ($thumbnails as $thumbnail) {
-			if ($thumbnail == $url) {
-				continue;
-			}
 			$thumbnail = elgg_normalize_url($thumbnail);
-			if (filter_var($thumbnail, FILTER_VALIDATE_URL)) {
-				$asset = $this->parse($thumbnail, $flush, false);
+			if (filter_var($thumbnail, FILTER_VALIDATE_URL) && $this->isImage($thumbnail)) {
```
Comment (hypeJunction) [inline classes/hypeJunction/Scraper/ScraperService.php]: You can remove both checks now. I added image validation to https://github.com/hypeJunction/http-parser/commit/84f613645efcf67616248c23456140f19e643ad8. If URL is not valid, it will fail to parse, so no need to check either.

File: classes/hypeJunction/Scraper/ScraperService.php [hunk 2]
```diff
@@ -373,4 +377,60 @@ public static function getHttpClientConfig() {
 		return elgg_trigger_plugin_hook('http:config', 'framework:scraper', null, $config);
 	}
 
+	/**
+	 * Determine if a given url is an image
+	 * 
+	 * @param type $url
+	 * @return boolean
+	 */
+	public function isImage($url) {
```
Comment (hypeJunction) [inline classes/hypeJunction/Scraper/ScraperService.php]: Can remove

**Comment by beck24** [comment]
removed checks added to http-parser

**Comment by hypeJunction** [comment]
Thanks
